name: "infra preview & deploy"

on:
  push:
    branches:
      - main
    paths:
      - "10_infra/**"
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.2.8
  TF_PROJECT: tastylog
  TF_ENVIRONMENT: dev

defaults:
  run:
    shell: bash
    working-directory: "10_infra/"

jobs:
  preview:
    name: "preview"
    runs-on: ubuntu-latest
    outputs: 
      # 【重要】wrapper: true にすることで outputs.exitcode が使えるようになります
      IF_PLAN_EXITCODE: ${{ steps.plan.outputs.exitcode }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          # 【重要】false から true に変更。これで exitcode をキャッチできます
          terraform_wrapper: true 

      - name: Terraform format
        run: terraform fmt -check

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: Terraform init
        run: terraform init -no-color

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan
        id: plan
        continue-on-error: true
        run: |
          terraform plan \
            -var "project=${{ env.TF_PROJECT }}" \
            -var "environment=${{ env.TF_ENVIRONMENT }}" \
            -var "username=${{ secrets.MYSQL_USERNAME }}" \
            -var "password=${{ secrets.MYSQL_PASSWORD }}" \
            -input=false \
            -no-color \
            -detailed-exitcode

      - name: Slack notify
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "C02G0N65NEN",
              "text": "Terraform Preview Result",
              "attachments": [
                {
                  "fallback": "Terraform Preview Result",
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "Terraform Preview Result",
                        "emoji": true
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                      }
                    }
                  ]
                }
              ]
            }

  deploy:
    name: "Deploy"
    needs: preview
    # 【重要】always()を入れ、かつ値が '2' (文字列) か 2 (数値) か不問にする判定式
    if: |
      always() && 
      needs.preview.result != 'skipped' && 
      (needs.preview.outputs.IF_PLAN_EXITCODE == '2' || needs.preview.outputs.IF_PLAN_EXITCODE == 2)
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: Terraform init
        run: terraform init -no-color

      - name: Terraform apply
        run: |
          terraform apply \
            -var "project=${{ env.TF_PROJECT }}" \
            -var "environment=${{ env.TF_ENVIRONMENT }}" \
            -var "username=${{ secrets.MYSQL_USERNAME }}" \
            -var "password=${{ secrets.MYSQL_PASSWORD }}" \
            -input=false \
            -no-color \
            -auto-approve